### PR TITLE
Transfer client side

### PR DESCRIPTION
**Pull request by ian-r-rose**
Partner of Quansight/jupyterlab-omnisci#90.

### CODE REVIEW

**Comment by saulshanabrook** [comment]
I can update this with the PR I just merged. Looks good!

**Comment by saulshanabrook** [comment]
I had a go at keeping the original history.

**Comment by ian-r-rose** [comment]
I find hundreds of unrelated commits kind of confusing

**Comment by saulshanabrook** [comment]
> I find hundreds of unrelated commits kind of confusing

Yeah, they are a bit, but I do like that we get to keep the original history and can see where the code came from.

**Comment by saulshanabrook** [comment]
🤷

**Comment by ian-r-rose** [comment]
Go ahead and merge when you're ready. It looks like one of my cleanup commits was lost, but I can reconstruct later

**Comment by saulshanabrook** [comment]
@ian-r-rose I think I merged them all in?

**Comment by ian-r-rose** [comment]
a29b588 looks like it was lost

**Comment by saulshanabrook** [comment]
@ian-r-rose Ah yeah, I wasn't sure if it was safe, I didn't know if Vega needed that property on the transform?

**Comment by ian-r-rose** [comment]
Ah good point.  I tested it and it seemed okay, but maybe there are cases when it is needed.

**Pull request merged**
