### PR TITLE
Delete yarn.lock

### PR DESCRIPTION
**Pull request by saulshanabrook**

### CODE REVIEW

**Comment by goanpeca** [comment]
Actually we should probably leave the yarn.lock on the repo?

We could add this to the scripts section so that we make sure to use yarn all the time.

```
  "scripts": {
    "preinstall": "node -e \"if (process.env.npm_execpath.indexOf('yarn') === -1) throw new Error('Use yarn for installing: https://yarnpkg.com/en/docs/install')\"",
```

A bit "harsh" but that way we make sure to have things updated the right way

**Comment by goanpeca** [comment]
With that suggestion we get for example:
```
[eval]:1
if (process.env.npm_execpath.indexOf('yarn') === -1) throw new Error('Use yarn for installing: https://yarnpkg.com/en/docs/install')
                                                     ^

Error: Use yarn for installing: https://yarnpkg.com/en/docs/install
    at [eval]:1:60
    at Script.runInThisContext (vm.js:116:20)
    at Object.runInThisContext (vm.js:306:38)
    at Object.<anonymous> ([eval]-wrapper:9:26)
    at Module._compile (internal/modules/cjs/loader.js:958:30)
    at evalScript (internal/process/execution.js:80:25)
    at internal/main/eval_string.js:23:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ibis-vega-transform@2.0.1 preinstall: `node -e "if (process.env.npm_execpath.indexOf('yarn') === -1) throw new Error('Use yarn for installing: https://yarnpkg.com/en/docs/install')"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ibis-vega-transform@2.0.1 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/gpena-castellanos/.npm/_logs/2019-12-09T18_00_22_787Z-debug.log
```

**Comment by saulshanabrook** [comment]
> Actually we should probably leave the yarn.lock on the repo?

I used to think we should then @kgryte convinced me we don't have to https://github.com/jupyterlab/jupyterlab-data-explorer/issues/84

**Comment by goanpeca** [comment]
Ok, then no need to "force" npm vs yarn?

**Comment by saulshanabrook** [comment]
@goanpeca Naw, it should be ok with either.

**Pull request merged**
